### ISSUE TITLE
UI 改进建议

### ISSUE THREAD

**Issue by entr0pia** [ztc1997/FakeDCBacklight#1]
这样就可以不用去翻看日志了
其中`等效亮度`指 `targetBright`

![image](https://user-images.githubusercontent.com/30486766/184838770-2d5aeec3-2af3-451f-9c1f-16b9205db3ce.png)

**Comment by ztc1997** [comment]
找不到有效的办法回传数据到模块，我试过直接在hook的地方发送广播会导致系统崩溃

**Comment by entr0pia** [comment]
那监听系统设置变量呢? 
屏幕亮度: `system` 中的 `screen_brightness`, 取值范围为[0,255]
极暗强度: `secure` 中的 `reduce_bright_colors_level`

![image](https://user-images.githubusercontent.com/30486766/184858883-bab07295-14bd-438f-8bdf-493c1ecf9bf5.png)

**Comment by ztc1997** [comment]
设置中的亮度和hal亮度不一样

**Comment by ztc1997** [comment]
989fc5a0ef6fc1a9b69ad23b209c13e2bbc99b32
