### ISSUE TITLE
小米12s MIUI14 指纹解锁后自动亮度过高

### ISSUE THREAD

**Issue by xqxian** [ztc1997/FakeDCBacklight#10]
# 问题描述

小米12s 升级 MIUI14 后，在黑暗环境中，息屏时通过指纹解锁进入桌面，自动亮度会过高：
![IMG_20230108_132240.jpg](https://user-images.githubusercontent.com/21199814/211181775-6a3a6537-2d80-4e3e-b0c4-f5774d6a3aec.jpg)
![IMG_20230108_132805.jpg](https://user-images.githubusercontent.com/21199814/211181885-4724ecdf-1985-4a6d-8185-759bae6600e5.jpg)

但如果先按实体键点亮屏幕，再通过指纹解锁进入桌面，则自动亮度正常：
![IMG_20230108_132225.jpg](https://user-images.githubusercontent.com/21199814/211181780-bae961b3-ffe7-4c4e-95e9-6e028b2c3707.jpg)
![IMG_20230108_132822.jpg](https://user-images.githubusercontent.com/21199814/211181897-42d0ac81-7385-49ec-b537-95024ccc7a0b.jpg)

关闭伪DC调光不会有这种现象，自动亮度一直都够低

**Comment by Ersiter** [comment]
我也有过亮度过高现象，但不是指纹解锁的时候。有时充足光照的情况下，亮度突然拉得很亮，此时自动亮度是打开的。然后我第一次关闭再打开自动亮度开关，亮度恢复正常；第二次关闭再打开自动亮度开关，亮度又过高了，以此类推……

**Comment by chenzeei** [comment]
12su 系统版本14.0.10 遇到了一模一样的问题

**Comment by xqxian** [comment]
最新版已修复，感谢！
