### ISSUE TITLE
一加 ace pro HAL 参数显示问题

### ISSUE THREAD

**Issue by fatinghenji** [ztc1997/FakeDCBacklight#9]
在使用了您的软件后，我发现似乎参数显示有问题。即使我在亮度设置中将亮度手动调整至最低，在软件中 HAL 亮度值依旧是 400%。这个数值是正确的吗？
下面的两张图是我目前正在使用的参数。
![Screenshot_2022-11-13-23-38-39-89_97550f1d11c73369bbee8f7d47965447](https://user-images.githubusercontent.com/37131177/201530515-4e4c1bed-a151-447c-abd5-6c5cb0be27d1.jpg)
![Screenshot_2022-11-13-23-37-14-22_da242479714f32383a59063166f0415c](https://user-images.githubusercontent.com/37131177/201530519-850fe4f8-dff1-4d45-8b3d-0be1d80e8047.jpg)

**Comment by ztc1997** [comment]
请注意看已有的信息。
README: `HAL的亮度值，不一定每台机型都是0~100%`
1.1.1 Realease note: `允许最低屏幕亮度大于100%（Oppo 某些设备亮度单位不一样）`（Oneplus 是 Oppo 子品牌）
